nstall:
- gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
- \curl -sSL https://get.rvm.io | bash 
- rvm install 2.1
- rvm use 2.1
script: 
- "rvm use 2.1"
- "cd ./src/test && ruby test_bot.rb"
